// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/iam/v1/iam.proto

package iamv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Environment int32

const (
	Environment_ENV_UNSPECIFIED Environment = 0
	Environment_PROD            Environment = 1
	Environment_STAGE           Environment = 2
	Environment_DEV             Environment = 3
)

// Enum value maps for Environment.
var (
	Environment_name = map[int32]string{
		0: "ENV_UNSPECIFIED",
		1: "PROD",
		2: "STAGE",
		3: "DEV",
	}
	Environment_value = map[string]int32{
		"ENV_UNSPECIFIED": 0,
		"PROD":            1,
		"STAGE":           2,
		"DEV":             3,
	}
)

func (x Environment) Enum() *Environment {
	p := new(Environment)
	*p = x
	return p
}

func (x Environment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Environment) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_iam_v1_iam_proto_enumTypes[0].Descriptor()
}

func (Environment) Type() protoreflect.EnumType {
	return &file_proto_iam_v1_iam_proto_enumTypes[0]
}

func (x Environment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Environment.Descriptor instead.
func (Environment) EnumDescriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{0}
}

type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Environment   Environment            `protobuf:"varint,3,opt,name=environment,proto3,enum=iam.v1.Environment" json:"environment,omitempty"`
	Id            string                 `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Labels        []string               `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"` // добавили обратно
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetEnvironment() Environment {
	if x != nil {
		return x.Environment
	}
	return Environment_ENV_UNSPECIFIED
}

func (x *Resource) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resource) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Resource) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type Role struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Permissions   []string               `protobuf:"bytes,2,rep,name=permissions,proto3" json:"permissions,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Role) Reset() {
	*x = Role{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Role) ProtoMessage() {}

func (x *Role) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Role.ProtoReflect.Descriptor instead.
func (*Role) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{1}
}

func (x *Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Role) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *Role) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type Subject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Justification string                 `protobuf:"bytes,2,opt,name=justification,proto3" json:"justification,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Subject) Reset() {
	*x = Subject{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Subject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Subject) ProtoMessage() {}

func (x *Subject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Subject.ProtoReflect.Descriptor instead.
func (*Subject) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{2}
}

func (x *Subject) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Subject) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

func (x *Subject) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AccessRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Subject            *Subject               `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	RequestedForUserId string                 `protobuf:"bytes,3,opt,name=requested_for_user_id,json=requestedForUserId,proto3" json:"requested_for_user_id,omitempty"`
	RequestedByUserId  string                 `protobuf:"bytes,4,opt,name=requested_by_user_id,json=requestedByUserId,proto3" json:"requested_by_user_id,omitempty"`
	DelegationReason   string                 `protobuf:"bytes,5,opt,name=delegation_reason,json=delegationReason,proto3" json:"delegation_reason,omitempty"`
	Resource           *Resource              `protobuf:"bytes,6,opt,name=resource,proto3" json:"resource,omitempty"`
	Roles              []*Role                `protobuf:"bytes,7,rep,name=roles,proto3" json:"roles,omitempty"`
	DurationValue      int64                  `protobuf:"varint,8,opt,name=duration_value,json=durationValue,proto3" json:"duration_value,omitempty"`
	DurationUnit       string                 `protobuf:"bytes,9,opt,name=duration_unit,json=durationUnit,proto3" json:"duration_unit,omitempty"`
	CreatedAt          *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{3}
}

func (x *AccessRequest) GetSubject() *Subject {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *AccessRequest) GetRequestedForUserId() string {
	if x != nil {
		return x.RequestedForUserId
	}
	return ""
}

func (x *AccessRequest) GetRequestedByUserId() string {
	if x != nil {
		return x.RequestedByUserId
	}
	return ""
}

func (x *AccessRequest) GetDelegationReason() string {
	if x != nil {
		return x.DelegationReason
	}
	return ""
}

func (x *AccessRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *AccessRequest) GetRoles() []*Role {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *AccessRequest) GetDurationValue() int64 {
	if x != nil {
		return x.DurationValue
	}
	return 0
}

func (x *AccessRequest) GetDurationUnit() string {
	if x != nil {
		return x.DurationUnit
	}
	return ""
}

func (x *AccessRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AccessRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type HRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ResourceId    string                 `protobuf:"bytes,2,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HRRequest) Reset() {
	*x = HRRequest{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HRRequest) ProtoMessage() {}

func (x *HRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HRRequest.ProtoReflect.Descriptor instead.
func (*HRRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{4}
}

func (x *HRRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *HRRequest) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type HRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Position      string                 `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	Department    string                 `protobuf:"bytes,3,opt,name=department,proto3" json:"department,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ManagerId     string                 `protobuf:"bytes,5,opt,name=manager_id,json=managerId,proto3" json:"manager_id,omitempty"`
	HrBp          string                 `protobuf:"bytes,6,opt,name=hr_bp,json=hrBp,proto3" json:"hr_bp,omitempty"`
	Groups        []string               `protobuf:"bytes,7,rep,name=groups,proto3" json:"groups,omitempty"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HRResponse) Reset() {
	*x = HRResponse{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HRResponse) ProtoMessage() {}

func (x *HRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HRResponse.ProtoReflect.Descriptor instead.
func (*HRResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{5}
}

func (x *HRResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *HRResponse) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *HRResponse) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *HRResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HRResponse) GetManagerId() string {
	if x != nil {
		return x.ManagerId
	}
	return ""
}

func (x *HRResponse) GetHrBp() string {
	if x != nil {
		return x.HrBp
	}
	return ""
}

func (x *HRResponse) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *HRResponse) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *HRResponse) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type WorkflowStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApproverIds   []string               `protobuf:"bytes,2,rep,name=approver_ids,json=approverIds,proto3" json:"approver_ids,omitempty"`
	Mode          string                 `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"` // ANY / ALL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowStep) Reset() {
	*x = WorkflowStep{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStep) ProtoMessage() {}

func (x *WorkflowStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStep.ProtoReflect.Descriptor instead.
func (*WorkflowStep) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{6}
}

func (x *WorkflowStep) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkflowStep) GetApproverIds() []string {
	if x != nil {
		return x.ApproverIds
	}
	return nil
}

func (x *WorkflowStep) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type WorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*WorkflowStep        `protobuf:"bytes,2,rep,name=steps,proto3" json:"steps,omitempty"`
	TotalSteps    int32                  `protobuf:"varint,3,opt,name=total_steps,json=totalSteps,proto3" json:"total_steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowResponse) Reset() {
	*x = WorkflowResponse{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowResponse) ProtoMessage() {}

func (x *WorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowResponse.ProtoReflect.Descriptor instead.
func (*WorkflowResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{7}
}

func (x *WorkflowResponse) GetSteps() []*WorkflowStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *WorkflowResponse) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

type IsApproverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StepIndex     int32                  `protobuf:"varint,1,opt,name=step_index,json=stepIndex,proto3" json:"step_index,omitempty"`
	ApproverId    string                 `protobuf:"bytes,2,opt,name=approver_id,json=approverId,proto3" json:"approver_id,omitempty"`
	Request       *AccessRequest         `protobuf:"bytes,3,opt,name=request,proto3" json:"request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsApproverRequest) Reset() {
	*x = IsApproverRequest{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsApproverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsApproverRequest) ProtoMessage() {}

func (x *IsApproverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsApproverRequest.ProtoReflect.Descriptor instead.
func (*IsApproverRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{8}
}

func (x *IsApproverRequest) GetStepIndex() int32 {
	if x != nil {
		return x.StepIndex
	}
	return 0
}

func (x *IsApproverRequest) GetApproverId() string {
	if x != nil {
		return x.ApproverId
	}
	return ""
}

func (x *IsApproverRequest) GetRequest() *AccessRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

type IsApproverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsApprover    bool                   `protobuf:"varint,1,opt,name=is_approver,json=isApprover,proto3" json:"is_approver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsApproverResponse) Reset() {
	*x = IsApproverResponse{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsApproverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsApproverResponse) ProtoMessage() {}

func (x *IsApproverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsApproverResponse.ProtoReflect.Descriptor instead.
func (*IsApproverResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{9}
}

func (x *IsApproverResponse) GetIsApprover() bool {
	if x != nil {
		return x.IsApprover
	}
	return false
}

type PolicyExplain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PolicyId      string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"` // baseline | augment | override | restrict
	Priority      int32                  `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	Matched       bool                   `protobuf:"varint,4,opt,name=matched,proto3" json:"matched,omitempty"`
	Reasons       []string               `protobuf:"bytes,5,rep,name=reasons,proto3" json:"reasons,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyExplain) Reset() {
	*x = PolicyExplain{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyExplain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyExplain) ProtoMessage() {}

func (x *PolicyExplain) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyExplain.ProtoReflect.Descriptor instead.
func (*PolicyExplain) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{10}
}

func (x *PolicyExplain) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyExplain) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PolicyExplain) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *PolicyExplain) GetMatched() bool {
	if x != nil {
		return x.Matched
	}
	return false
}

func (x *PolicyExplain) GetReasons() []string {
	if x != nil {
		return x.Reasons
	}
	return nil
}

type ExplainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*PolicyExplain       `protobuf:"bytes,2,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExplainResponse) Reset() {
	*x = ExplainResponse{}
	mi := &file_proto_iam_v1_iam_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExplainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExplainResponse) ProtoMessage() {}

func (x *ExplainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_v1_iam_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExplainResponse.ProtoReflect.Descriptor instead.
func (*ExplainResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_v1_iam_proto_rawDescGZIP(), []int{11}
}

func (x *ExplainResponse) GetPolicies() []*PolicyExplain {
	if x != nil {
		return x.Policies
	}
	return nil
}

var File_proto_iam_v1_iam_proto protoreflect.FileDescriptor

const file_proto_iam_v1_iam_proto_rawDesc = "" +
	"\n" +
	"\x16proto/iam/v1/iam.proto\x12\x06iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x92\x02\n" +
	"\bResource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x125\n" +
	"\venvironment\x18\x03 \x01(\x0e2\x13.iam.v1.EnvironmentR\venvironment\x12\x0e\n" +
	"\x02id\x18\x04 \x01(\tR\x02id\x12@\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v2 .iam.v1.Resource.AttributesEntryR\n" +
	"attributes\x12\x16\n" +
	"\x06labels\x18\x06 \x03(\tR\x06labels\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb9\x01\n" +
	"\x04Role\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vpermissions\x18\x02 \x03(\tR\vpermissions\x12<\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\x1c.iam.v1.Role.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc0\x01\n" +
	"\aSubject\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12$\n" +
	"\rjustification\x18\x02 \x01(\tR\rjustification\x129\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1d.iam.v1.Subject.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdf\x03\n" +
	"\rAccessRequest\x12)\n" +
	"\asubject\x18\x02 \x01(\v2\x0f.iam.v1.SubjectR\asubject\x121\n" +
	"\x15requested_for_user_id\x18\x03 \x01(\tR\x12requestedForUserId\x12/\n" +
	"\x14requested_by_user_id\x18\x04 \x01(\tR\x11requestedByUserId\x12+\n" +
	"\x11delegation_reason\x18\x05 \x01(\tR\x10delegationReason\x12,\n" +
	"\bresource\x18\x06 \x01(\v2\x10.iam.v1.ResourceR\bresource\x12\"\n" +
	"\x05roles\x18\a \x03(\v2\f.iam.v1.RoleR\x05roles\x12%\n" +
	"\x0eduration_value\x18\b \x01(\x03R\rdurationValue\x12#\n" +
	"\rduration_unit\x18\t \x01(\tR\fdurationUnit\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"E\n" +
	"\tHRRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vresource_id\x18\x02 \x01(\tR\n" +
	"resourceId\"\xfc\x02\n" +
	"\n" +
	"HRResponse\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\tR\bposition\x12\x1e\n" +
	"\n" +
	"department\x18\x03 \x01(\tR\n" +
	"department\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"manager_id\x18\x05 \x01(\tR\tmanagerId\x12\x13\n" +
	"\x05hr_bp\x18\x06 \x01(\tR\x04hrBp\x12\x16\n" +
	"\x06groups\x18\a \x03(\tR\x06groups\x12.\n" +
	"\x04time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12B\n" +
	"\n" +
	"attributes\x18\t \x03(\v2\".iam.v1.HRResponse.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"Y\n" +
	"\fWorkflowStep\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\fapprover_ids\x18\x02 \x03(\tR\vapproverIds\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\"_\n" +
	"\x10WorkflowResponse\x12*\n" +
	"\x05steps\x18\x02 \x03(\v2\x14.iam.v1.WorkflowStepR\x05steps\x12\x1f\n" +
	"\vtotal_steps\x18\x03 \x01(\x05R\n" +
	"totalSteps\"\x84\x01\n" +
	"\x11IsApproverRequest\x12\x1d\n" +
	"\n" +
	"step_index\x18\x01 \x01(\x05R\tstepIndex\x12\x1f\n" +
	"\vapprover_id\x18\x02 \x01(\tR\n" +
	"approverId\x12/\n" +
	"\arequest\x18\x03 \x01(\v2\x15.iam.v1.AccessRequestR\arequest\"5\n" +
	"\x12IsApproverResponse\x12\x1f\n" +
	"\vis_approver\x18\x01 \x01(\bR\n" +
	"isApprover\"\x90\x01\n" +
	"\rPolicyExplain\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\x05R\bpriority\x12\x18\n" +
	"\amatched\x18\x04 \x01(\bR\amatched\x12\x18\n" +
	"\areasons\x18\x05 \x03(\tR\areasons\"D\n" +
	"\x0fExplainResponse\x121\n" +
	"\bpolicies\x18\x02 \x03(\v2\x15.iam.v1.PolicyExplainR\bpolicies*@\n" +
	"\vEnvironment\x12\x13\n" +
	"\x0fENV_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04PROD\x10\x01\x12\t\n" +
	"\x05STAGE\x10\x02\x12\a\n" +
	"\x03DEV\x10\x032\xda\x01\n" +
	"\x03IAM\x12F\n" +
	"\x13CreateAccessRequest\x12\x15.iam.v1.AccessRequest\x1a\x18.iam.v1.WorkflowResponse\x12F\n" +
	"\x14ExplainAccessRequest\x12\x15.iam.v1.AccessRequest\x1a\x17.iam.v1.ExplainResponse\x12C\n" +
	"\n" +
	"IsApprover\x12\x19.iam.v1.IsApproverRequest\x1a\x1a.iam.v1.IsApproverResponse2?\n" +
	"\tHRService\x122\n" +
	"\tGetHRInfo\x12\x11.iam.v1.HRRequest\x1a\x12.iam.v1.HRResponseB\x18Z\x16nir/proto/iam/v1;iamv1b\x06proto3"

var (
	file_proto_iam_v1_iam_proto_rawDescOnce sync.Once
	file_proto_iam_v1_iam_proto_rawDescData []byte
)

func file_proto_iam_v1_iam_proto_rawDescGZIP() []byte {
	file_proto_iam_v1_iam_proto_rawDescOnce.Do(func() {
		file_proto_iam_v1_iam_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_iam_v1_iam_proto_rawDesc), len(file_proto_iam_v1_iam_proto_rawDesc)))
	})
	return file_proto_iam_v1_iam_proto_rawDescData
}

var file_proto_iam_v1_iam_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_iam_v1_iam_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_iam_v1_iam_proto_goTypes = []any{
	(Environment)(0),              // 0: iam.v1.Environment
	(*Resource)(nil),              // 1: iam.v1.Resource
	(*Role)(nil),                  // 2: iam.v1.Role
	(*Subject)(nil),               // 3: iam.v1.Subject
	(*AccessRequest)(nil),         // 4: iam.v1.AccessRequest
	(*HRRequest)(nil),             // 5: iam.v1.HRRequest
	(*HRResponse)(nil),            // 6: iam.v1.HRResponse
	(*WorkflowStep)(nil),          // 7: iam.v1.WorkflowStep
	(*WorkflowResponse)(nil),      // 8: iam.v1.WorkflowResponse
	(*IsApproverRequest)(nil),     // 9: iam.v1.IsApproverRequest
	(*IsApproverResponse)(nil),    // 10: iam.v1.IsApproverResponse
	(*PolicyExplain)(nil),         // 11: iam.v1.PolicyExplain
	(*ExplainResponse)(nil),       // 12: iam.v1.ExplainResponse
	nil,                           // 13: iam.v1.Resource.AttributesEntry
	nil,                           // 14: iam.v1.Role.AttributesEntry
	nil,                           // 15: iam.v1.Subject.MetadataEntry
	nil,                           // 16: iam.v1.HRResponse.AttributesEntry
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_proto_iam_v1_iam_proto_depIdxs = []int32{
	0,  // 0: iam.v1.Resource.environment:type_name -> iam.v1.Environment
	13, // 1: iam.v1.Resource.attributes:type_name -> iam.v1.Resource.AttributesEntry
	14, // 2: iam.v1.Role.attributes:type_name -> iam.v1.Role.AttributesEntry
	15, // 3: iam.v1.Subject.metadata:type_name -> iam.v1.Subject.MetadataEntry
	3,  // 4: iam.v1.AccessRequest.subject:type_name -> iam.v1.Subject
	1,  // 5: iam.v1.AccessRequest.resource:type_name -> iam.v1.Resource
	2,  // 6: iam.v1.AccessRequest.roles:type_name -> iam.v1.Role
	17, // 7: iam.v1.AccessRequest.created_at:type_name -> google.protobuf.Timestamp
	17, // 8: iam.v1.AccessRequest.updated_at:type_name -> google.protobuf.Timestamp
	17, // 9: iam.v1.HRResponse.time:type_name -> google.protobuf.Timestamp
	16, // 10: iam.v1.HRResponse.attributes:type_name -> iam.v1.HRResponse.AttributesEntry
	7,  // 11: iam.v1.WorkflowResponse.steps:type_name -> iam.v1.WorkflowStep
	4,  // 12: iam.v1.IsApproverRequest.request:type_name -> iam.v1.AccessRequest
	11, // 13: iam.v1.ExplainResponse.policies:type_name -> iam.v1.PolicyExplain
	4,  // 14: iam.v1.IAM.CreateAccessRequest:input_type -> iam.v1.AccessRequest
	4,  // 15: iam.v1.IAM.ExplainAccessRequest:input_type -> iam.v1.AccessRequest
	9,  // 16: iam.v1.IAM.IsApprover:input_type -> iam.v1.IsApproverRequest
	5,  // 17: iam.v1.HRService.GetHRInfo:input_type -> iam.v1.HRRequest
	8,  // 18: iam.v1.IAM.CreateAccessRequest:output_type -> iam.v1.WorkflowResponse
	12, // 19: iam.v1.IAM.ExplainAccessRequest:output_type -> iam.v1.ExplainResponse
	10, // 20: iam.v1.IAM.IsApprover:output_type -> iam.v1.IsApproverResponse
	6,  // 21: iam.v1.HRService.GetHRInfo:output_type -> iam.v1.HRResponse
	18, // [18:22] is the sub-list for method output_type
	14, // [14:18] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_proto_iam_v1_iam_proto_init() }
func file_proto_iam_v1_iam_proto_init() {
	if File_proto_iam_v1_iam_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_iam_v1_iam_proto_rawDesc), len(file_proto_iam_v1_iam_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_iam_v1_iam_proto_goTypes,
		DependencyIndexes: file_proto_iam_v1_iam_proto_depIdxs,
		EnumInfos:         file_proto_iam_v1_iam_proto_enumTypes,
		MessageInfos:      file_proto_iam_v1_iam_proto_msgTypes,
	}.Build()
	File_proto_iam_v1_iam_proto = out.File
	file_proto_iam_v1_iam_proto_goTypes = nil
	file_proto_iam_v1_iam_proto_depIdxs = nil
}
