// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/iam/v1/iam.proto

package iamv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IAM_CreateAccessRequest_FullMethodName  = "/iam.v1.IAM/CreateAccessRequest"
	IAM_ExplainAccessRequest_FullMethodName = "/iam.v1.IAM/ExplainAccessRequest"
	IAM_IsApprover_FullMethodName           = "/iam.v1.IAM/IsApprover"
)

// IAMClient is the client API for IAM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IAMClient interface {
	CreateAccessRequest(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*WorkflowResponse, error)
	ExplainAccessRequest(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*ExplainResponse, error)
	IsApprover(ctx context.Context, in *IsApproverRequest, opts ...grpc.CallOption) (*IsApproverResponse, error)
}

type iAMClient struct {
	cc grpc.ClientConnInterface
}

func NewIAMClient(cc grpc.ClientConnInterface) IAMClient {
	return &iAMClient{cc}
}

func (c *iAMClient) CreateAccessRequest(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*WorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WorkflowResponse)
	err := c.cc.Invoke(ctx, IAM_CreateAccessRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) ExplainAccessRequest(ctx context.Context, in *AccessRequest, opts ...grpc.CallOption) (*ExplainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainResponse)
	err := c.cc.Invoke(ctx, IAM_ExplainAccessRequest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMClient) IsApprover(ctx context.Context, in *IsApproverRequest, opts ...grpc.CallOption) (*IsApproverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IsApproverResponse)
	err := c.cc.Invoke(ctx, IAM_IsApprover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IAMServer is the server API for IAM service.
// All implementations must embed UnimplementedIAMServer
// for forward compatibility.
type IAMServer interface {
	CreateAccessRequest(context.Context, *AccessRequest) (*WorkflowResponse, error)
	ExplainAccessRequest(context.Context, *AccessRequest) (*ExplainResponse, error)
	IsApprover(context.Context, *IsApproverRequest) (*IsApproverResponse, error)
	mustEmbedUnimplementedIAMServer()
}

// UnimplementedIAMServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIAMServer struct{}

func (UnimplementedIAMServer) CreateAccessRequest(context.Context, *AccessRequest) (*WorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccessRequest not implemented")
}
func (UnimplementedIAMServer) ExplainAccessRequest(context.Context, *AccessRequest) (*ExplainResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExplainAccessRequest not implemented")
}
func (UnimplementedIAMServer) IsApprover(context.Context, *IsApproverRequest) (*IsApproverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IsApprover not implemented")
}
func (UnimplementedIAMServer) mustEmbedUnimplementedIAMServer() {}
func (UnimplementedIAMServer) testEmbeddedByValue()             {}

// UnsafeIAMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IAMServer will
// result in compilation errors.
type UnsafeIAMServer interface {
	mustEmbedUnimplementedIAMServer()
}

func RegisterIAMServer(s grpc.ServiceRegistrar, srv IAMServer) {
	// If the following call panics, it indicates UnimplementedIAMServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IAM_ServiceDesc, srv)
}

func _IAM_CreateAccessRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).CreateAccessRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_CreateAccessRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).CreateAccessRequest(ctx, req.(*AccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_ExplainAccessRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).ExplainAccessRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_ExplainAccessRequest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).ExplainAccessRequest(ctx, req.(*AccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAM_IsApprover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsApproverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServer).IsApprover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAM_IsApprover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServer).IsApprover(ctx, req.(*IsApproverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IAM_ServiceDesc is the grpc.ServiceDesc for IAM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IAM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.v1.IAM",
	HandlerType: (*IAMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccessRequest",
			Handler:    _IAM_CreateAccessRequest_Handler,
		},
		{
			MethodName: "ExplainAccessRequest",
			Handler:    _IAM_ExplainAccessRequest_Handler,
		},
		{
			MethodName: "IsApprover",
			Handler:    _IAM_IsApprover_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/iam/v1/iam.proto",
}

const (
	HRService_GetHRInfo_FullMethodName = "/iam.v1.HRService/GetHRInfo"
)

// HRServiceClient is the client API for HRService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HRServiceClient interface {
	GetHRInfo(ctx context.Context, in *HRRequest, opts ...grpc.CallOption) (*HRResponse, error)
}

type hRServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHRServiceClient(cc grpc.ClientConnInterface) HRServiceClient {
	return &hRServiceClient{cc}
}

func (c *hRServiceClient) GetHRInfo(ctx context.Context, in *HRRequest, opts ...grpc.CallOption) (*HRResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HRResponse)
	err := c.cc.Invoke(ctx, HRService_GetHRInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HRServiceServer is the server API for HRService service.
// All implementations must embed UnimplementedHRServiceServer
// for forward compatibility.
type HRServiceServer interface {
	GetHRInfo(context.Context, *HRRequest) (*HRResponse, error)
	mustEmbedUnimplementedHRServiceServer()
}

// UnimplementedHRServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHRServiceServer struct{}

func (UnimplementedHRServiceServer) GetHRInfo(context.Context, *HRRequest) (*HRResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHRInfo not implemented")
}
func (UnimplementedHRServiceServer) mustEmbedUnimplementedHRServiceServer() {}
func (UnimplementedHRServiceServer) testEmbeddedByValue()                   {}

// UnsafeHRServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HRServiceServer will
// result in compilation errors.
type UnsafeHRServiceServer interface {
	mustEmbedUnimplementedHRServiceServer()
}

func RegisterHRServiceServer(s grpc.ServiceRegistrar, srv HRServiceServer) {
	// If the following call panics, it indicates UnimplementedHRServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HRService_ServiceDesc, srv)
}

func _HRService_GetHRInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HRRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HRServiceServer).GetHRInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HRService_GetHRInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HRServiceServer).GetHRInfo(ctx, req.(*HRRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HRService_ServiceDesc is the grpc.ServiceDesc for HRService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HRService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.v1.HRService",
	HandlerType: (*HRServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHRInfo",
			Handler:    _HRService_GetHRInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/iam/v1/iam.proto",
}
